// ============================================
// Main Entry Point
// ============================================

import './styles/base.css';
import './styles/components.css';
import './styles/utilities.css';
import './styles/layout.css';
import { initApp } from './app';

// Initialize the application
document.addEventListener('DOMContentLoaded', () => {
  initApp();
});

// Register service worker for PWA
if ('serviceWorker' in navigator) {
  window.addEventListener('load', async () => {
    try {
      // Service worker will be generated by vite-plugin-pwa
      // await navigator.serviceWorker.register('/sw.js');
      console.log('PWA ready');
    } catch (error) {
      console.log('PWA registration skipped:', error);
    }
  });
}
